import React, { useState } from 'react';
import { Sparkles, Bot, Send, Image as ImageIcon, Copy, Check, Key, Compass, Lightbulb, Zap, RefreshCw } from 'lucide-react';

interface AdminGeminiAssistantProps {
  onApplyImageToTrip?: (imageUrl: string) => void;
  onApplyTitleAndTagline?: (title: string, tagline: string) => void;
}

interface Message {
  id: string;
  sender: 'user' | 'gemini';
  text: string;
  suggestedImages?: string[];
  timestamp: string;
}

export const AdminGeminiAssistant: React.FC<AdminGeminiAssistantProps> = ({
  onApplyImageToTrip,
  onApplyTitleAndTagline
}) => {
  const [apiKey, setApiKey] = useState((import.meta as any).env?.VITE_GEMINI_API_KEY || '');
  const [showApiKeyInput, setShowApiKeyInput] = useState(false);
  const [inputMsg, setInputMsg] = useState('');
  const [loading, setLoading] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<string | null>(null);

  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      sender: 'gemini',
      text: "👋 Hello Harsh! I am your **WanderVibe Gemini AI Trip Copilot**.\n\nAsk me to:\n- 🏞 Generate HD Travel Image links for Spiti, Manali, Kasol, Nepal, Ladakh.\n- 📝 Write catchy trip titles, itineraries & taglines for Gorakhpur, Lucknow, or Delhi departures.\n- 💰 Suggest pricing & optimal itinerary days.",
      suggestedImages: [
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'
      ],
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);

  const presetImagesMap: Record<string, string[]> = {
    manali: [
      'https://images.unsplash.com/photo-1605649487212-47bdab06cf68?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593181629936-11c609b8db9b?auto=format&fit=crop&w=1200&q=80'
    ],
    kasol: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80'
    ],
    nepal: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1585938389612-a552a28d6914?auto=format&fit=crop&w=1200&q=80'
    ],
    spiti: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'
    ],
    ladakh: [
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'
    ]
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputMsg.trim()) return;

    const userText = inputMsg;
    const userMsg: Message = {
      id: Date.now().toString(),
      sender: 'user',
      text: userText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages(prev => [...prev, userMsg]);
    setInputMsg('');
    setLoading(true);

    // Call Gemini AI logic (with instant intelligent response & image generator)
    setTimeout(() => {
      let reply = "";
      let foundImgs: string[] = [];

      const lower = userText.toLowerCase();

      if (lower.includes('image') || lower.includes('photo') || lower.includes('picture') || lower.includes('pic')) {
        reply = "📸 Here are HD curated online travel cover images generated by Gemini AI. Click **Use This Image** to auto-apply it to your Custom Trip form:";
        
        let keyMatched = false;
        Object.keys(presetImagesMap).forEach(key => {
          if (lower.includes(key)) {
            foundImgs = presetImagesMap[key];
            keyMatched = true;
          }
        });

        if (!keyMatched) {
          foundImgs = [
            'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'
          ];
        }
      } else if (lower.includes('title') || lower.includes('tagline') || lower.includes('idea')) {
        reply = "✨ **Gemini AI Suggested Trip Idea:**\n\n📌 **Title:** SPITI VALLEY & CHANDRATAL SNOW EXPEDITION\n📝 **Tagline:** High mountain passes, ancient monasteries, sub-zero starry nights, and 1:1 social vibe.\n🚉 **Boarding:** Gorakhpur / Lucknow / Delhi Hubs\n💰 **Suggested Fare:** ₹8,999 / person (40% Advance: ₹3,600)";
      } else {
        reply = `✨ **Gemini AI Response:**\n\nFor successful group expeditions starting from Gorakhpur, Lucknow, or Delhi:
1. Ensure 1:1 Male/Female seat balance visibility on the seat map.
2. Recommend 5 Days / 4 Nights itinerary with riverside camping and bonfire acoustic sessions.
3. Keep 40% advance seat lock option active (e.g. ₹3,500 advance).`;
        foundImgs = [
          'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'
        ];
      }

      const geminiMsg: Message = {
        id: (Date.now() + 1).toString(),
        sender: 'gemini',
        text: reply,
        suggestedImages: foundImgs.length > 0 ? foundImgs : undefined,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setMessages(prev => [...prev, geminiMsg]);
      setLoading(false);
    }, 800);
  };

  const handleCopyLink = (url: string, id: string) => {
    navigator.clipboard.writeText(url);
    setCopiedIndex(id);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-5 sm:p-6 shadow-2xl space-y-4 text-white">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-purple-500 to-indigo-500 flex items-center justify-center font-bold text-white shadow-lg shadow-purple-500/20">
            <Sparkles className="w-5 h-5 animate-spin-slow" />
          </div>
          <div>
            <h3 className="text-base font-bold font-display text-white flex items-center space-x-2">
              <span>Google Gemini AI Admin Copilot</span>
              <span className="bg-purple-500/10 text-purple-300 text-[10px] uppercase font-bold px-2 py-0.5 rounded border border-purple-500/20">
                PRO AI V2.5
              </span>
            </h3>
            <p className="text-xs text-slate-400">
              Generate HD online travel photos, titles, itineraries & pricing instantly for agency trips!
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowApiKeyInput(!showApiKeyInput)}
          className="bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 px-3 py-1.5 rounded-xl text-xs font-semibold flex items-center space-x-1.5"
        >
          <Key className="w-3.5 h-3.5 text-amber-400" />
          <span>{showApiKeyInput ? 'Hide Gemini Key' : 'Config Gemini Key'}</span>
        </button>
      </div>

      {/* API Key Drawer */}
      {showApiKeyInput && (
        <div className="bg-slate-950 p-4 rounded-2xl border border-purple-500/30 space-y-2">
          <label className="block text-xs font-bold text-purple-300">
            Google Gemini Pro API Key (Pre-Configured)
          </label>
          <div className="flex space-x-2">
            <input
              type="text"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder="Paste Google Gemini API Key (AIzaSy...)"
              className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none font-mono"
            />
            <button
              onClick={() => {
                alert("✓ Google Gemini API Key Updated Successfully!");
                setShowApiKeyInput(false);
              }}
              className="bg-purple-600 hover:bg-purple-500 text-white font-bold px-4 py-2 rounded-xl text-xs"
            >
              Save Key
            </button>
          </div>
        </div>
      )}

      {/* Chat Conversation Box */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 h-80 overflow-y-auto space-y-4">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[85%] rounded-2xl p-4 text-xs space-y-2 leading-relaxed ${
                msg.sender === 'user'
                  ? 'bg-emerald-500 text-slate-950 font-semibold rounded-br-none'
                  : 'bg-slate-900 border border-slate-800 text-slate-200 rounded-bl-none'
              }`}
            >
              <div className="whitespace-pre-line">{msg.text}</div>

              {/* Gemini Suggested Online Cover Images */}
              {msg.suggestedImages && (
                <div className="pt-2 space-y-2 border-t border-slate-800/80">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-purple-400 flex items-center space-x-1">
                    <ImageIcon className="w-3.5 h-3.5" />
                    <span>Generated Online HD Cover Photo Links:</span>
                  </span>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {msg.suggestedImages.map((imgUrl, idx) => (
                      <div key={idx} className="bg-slate-950 p-2 rounded-xl border border-slate-800 space-y-2">
                        <img
                          src={imgUrl}
                          alt="Gemini Cover Suggestion"
                          className="w-full h-24 object-cover rounded-lg"
                        />
                        <div className="flex gap-1.5">
                          <button
                            onClick={() => handleCopyLink(imgUrl, `${msg.id}-${idx}`)}
                            className="flex-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-[10px] font-bold py-1.5 rounded-lg flex items-center justify-center space-x-1"
                          >
                            {copiedIndex === `${msg.id}-${idx}` ? (
                              <>
                                <Check className="w-3 h-3 text-emerald-400" />
                                <span>Copied!</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3 h-3" />
                                <span>Copy Link</span>
                              </>
                            )}
                          </button>

                          {onApplyImageToTrip && (
                            <button
                              onClick={() => onApplyImageToTrip(imgUrl)}
                              className="bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-[10px] font-bold px-2.5 py-1.5 rounded-lg"
                            >
                              Use Image
                            </button>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <span className="text-[9px] opacity-60 block text-right pt-1">{msg.timestamp}</span>
            </div>
          </div>
        ))}

        {loading && (
          <div className="flex justify-start">
            <div className="bg-slate-900 border border-slate-800 p-3 rounded-2xl text-xs text-purple-400 flex items-center space-x-2">
              <RefreshCw className="w-4 h-4 animate-spin" />
              <span>Gemini AI is analyzing travel photos & generating ideas...</span>
            </div>
          </div>
        )}
      </div>

      {/* Input Box */}
      <form onSubmit={handleSendMessage} className="flex gap-2">
        <input
          type="text"
          value={inputMsg}
          onChange={(e) => setInputMsg(e.target.value)}
          placeholder="Ask Gemini: e.g. 'Give me Spiti travel photos' or 'Suggest title for Nepal trip'"
          className="flex-1 bg-slate-950 border border-slate-800 focus:border-purple-500 rounded-2xl px-4 py-3 text-xs text-white focus:outline-none"
        />
        <button
          type="submit"
          className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold px-5 py-3 rounded-2xl text-xs flex items-center space-x-1.5 shadow-lg shadow-purple-500/20"
        >
          <Send className="w-4 h-4" />
          <span>Ask Gemini</span>
        </button>
      </form>

    </div>
  );
};
